development:
  clients:
    default:
      database: opst-development
      hosts:
        - ds159707.mlab.com:59707
      options:
          max_pool_size: 5
          user: user
          password: password
          auth_mech: :scram
  options:
        raise_not_found_error: false
test:
  clients:
    default:
      database: tracker_test
      hosts:
        - ds159707.mlab.com:59707
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: tracker_opst
      hosts:
        - ds047315.mlab.com:47315
      options:
          max_pool_size: 5
          user: user
          password: password
          auth_mech: :scram
  options:
        raise_not_found_error: false